// Genki 元気 Tracker — Food Nutrition Database
// Owner: data agent. Plain script (no imports/exports) — assigns to window.
// Schema: { key, name, category, serving, servingG, calories, proteinG, carbsG, fatG, sodiumMg, sugarG, fiberG }
// Sodium values are prioritised for accuracy (many hawker/Asian dishes are very high-sodium).

window.FOOD_CATEGORIES = ["hawker","japanese","chinese","western","breakfast","proteins","fruits","vegetables","snacks","desserts","drinks","condiments"];

window.FOOD_DB = [
  { key: 'chicken-rice-plain', name: 'Hainanese Chicken Rice (steamed)', category: 'hawker', serving: '1 plate', servingG: 400, calories: 600, proteinG: 35, carbsG: 65, fatG: 20, sodiumMg: 900, sugarG: 3, fiberG: 2 },
  { key: 'chicken-rice-roasted', name: 'Roasted Chicken Rice', category: 'hawker', serving: '1 plate', servingG: 400, calories: 620, proteinG: 33, carbsG: 66, fatG: 22, sodiumMg: 950, sugarG: 3, fiberG: 2 },
  { key: 'laksa', name: 'Laksa', category: 'hawker', serving: '1 bowl', servingG: 500, calories: 650, proteinG: 20, carbsG: 55, fatG: 38, sodiumMg: 1650, sugarG: 6, fiberG: 3 },
  { key: 'char-kway-teow', name: 'Char Kway Teow', category: 'hawker', serving: '1 plate', servingG: 350, calories: 740, proteinG: 20, carbsG: 75, fatG: 40, sodiumMg: 1400, sugarG: 5, fiberG: 3 },
  { key: 'mee-goreng', name: 'Mee Goreng', category: 'hawker', serving: '1 plate', servingG: 350, calories: 560, proteinG: 15, carbsG: 70, fatG: 24, sodiumMg: 1100, sugarG: 8, fiberG: 3 },
  { key: 'hokkien-mee', name: 'Hokkien Mee', category: 'hawker', serving: '1 plate', servingG: 400, calories: 600, proteinG: 25, carbsG: 60, fatG: 26, sodiumMg: 1200, sugarG: 3, fiberG: 2 },
  { key: 'bak-chor-mee', name: 'Bak Chor Mee', category: 'hawker', serving: '1 bowl', servingG: 400, calories: 480, proteinG: 22, carbsG: 60, fatG: 15, sodiumMg: 1300, sugarG: 4, fiberG: 2 },
  { key: 'wonton-noodle-dry', name: 'Wonton Noodle (dry, tossed)', category: 'hawker', serving: '1 bowl', servingG: 350, calories: 450, proteinG: 18, carbsG: 65, fatG: 12, sodiumMg: 1100, sugarG: 5, fiberG: 2 },
  { key: 'fishball-noodle-soup', name: 'Fishball Noodle Soup', category: 'hawker', serving: '1 bowl', servingG: 400, calories: 380, proteinG: 20, carbsG: 55, fatG: 8, sodiumMg: 1250, sugarG: 3, fiberG: 2 },
  { key: 'satay-chicken', name: 'Chicken Satay (with peanut sauce)', category: 'hawker', serving: '5 sticks', servingG: 150, calories: 350, proteinG: 28, carbsG: 15, fatG: 20, sodiumMg: 600, sugarG: 10, fiberG: 1 },
  { key: 'satay-beef', name: 'Beef Satay (with peanut sauce)', category: 'hawker', serving: '5 sticks', servingG: 150, calories: 380, proteinG: 27, carbsG: 14, fatG: 24, sodiumMg: 620, sugarG: 9, fiberG: 1 },
  { key: 'rojak', name: 'Rojak', category: 'hawker', serving: '1 plate', servingG: 300, calories: 420, proteinG: 8, carbsG: 55, fatG: 18, sodiumMg: 700, sugarG: 25, fiberG: 5 },
  { key: 'popiah', name: 'Popiah', category: 'hawker', serving: '2 rolls', servingG: 200, calories: 300, proteinG: 8, carbsG: 45, fatG: 9, sodiumMg: 650, sugarG: 6, fiberG: 4 },
  { key: 'carrot-cake-fried-white', name: 'Fried Carrot Cake (white, savoury)', category: 'hawker', serving: '1 plate', servingG: 300, calories: 500, proteinG: 10, carbsG: 60, fatG: 24, sodiumMg: 900, sugarG: 4, fiberG: 2 },
  { key: 'carrot-cake-fried-black', name: 'Fried Carrot Cake (black, sweet)', category: 'hawker', serving: '1 plate', servingG: 300, calories: 550, proteinG: 9, carbsG: 75, fatG: 22, sodiumMg: 750, sugarG: 15, fiberG: 2 },
  { key: 'nasi-lemak', name: 'Nasi Lemak (with egg, anchovies, sambal)', category: 'hawker', serving: '1 plate', servingG: 400, calories: 700, proteinG: 22, carbsG: 80, fatG: 32, sodiumMg: 1000, sugarG: 5, fiberG: 3 },
  { key: 'roti-prata-plain', name: 'Roti Prata (plain)', category: 'hawker', serving: '2 pieces', servingG: 200, calories: 400, proteinG: 8, carbsG: 55, fatG: 17, sodiumMg: 500, sugarG: 2, fiberG: 2 },
  { key: 'roti-prata-egg', name: 'Roti Prata (egg)', category: 'hawker', serving: '1 piece', servingG: 150, calories: 350, proteinG: 10, carbsG: 40, fatG: 17, sodiumMg: 480, sugarG: 2, fiberG: 1 },
  { key: 'curry-chicken', name: 'Chicken Curry', category: 'hawker', serving: '1 bowl', servingG: 300, calories: 380, proteinG: 25, carbsG: 12, fatG: 26, sodiumMg: 850, sugarG: 4, fiberG: 2 },
  { key: 'fish-head-curry', name: 'Fish Head Curry', category: 'hawker', serving: '1 serving', servingG: 500, calories: 550, proteinG: 40, carbsG: 20, fatG: 32, sodiumMg: 1400, sugarG: 5, fiberG: 3 },
  { key: 'bak-kut-teh', name: 'Bak Kut Teh', category: 'hawker', serving: '1 bowl', servingG: 400, calories: 450, proteinG: 30, carbsG: 8, fatG: 32, sodiumMg: 1500, sugarG: 2, fiberG: 1 },
  { key: 'chilli-crab', name: 'Chilli Crab (half crab, with bun)', category: 'hawker', serving: '1 serving', servingG: 400, calories: 550, proteinG: 35, carbsG: 30, fatG: 30, sodiumMg: 1300, sugarG: 12, fiberG: 2 },
  { key: 'oyster-omelette', name: 'Oyster Omelette', category: 'hawker', serving: '1 plate', servingG: 300, calories: 500, proteinG: 18, carbsG: 35, fatG: 32, sodiumMg: 1100, sugarG: 2, fiberG: 1 },
  { key: 'economic-rice-3-dishes', name: 'Economic Rice (rice + 3 dishes)', category: 'hawker', serving: '1 plate', servingG: 450, calories: 650, proteinG: 25, carbsG: 75, fatG: 26, sodiumMg: 1200, sugarG: 3, fiberG: 4 },
  { key: 'mala-xiang-guo', name: 'Mala Xiang Guo', category: 'hawker', serving: '1 bowl', servingG: 400, calories: 600, proteinG: 30, carbsG: 30, fatG: 38, sodiumMg: 1600, sugarG: 5, fiberG: 3 },
  { key: 'yong-tau-foo', name: 'Yong Tau Foo (soup)', category: 'hawker', serving: '1 bowl', servingG: 350, calories: 300, proteinG: 20, carbsG: 25, fatG: 12, sodiumMg: 1100, sugarG: 3, fiberG: 3 },
  { key: 'prawn-noodle-soup', name: 'Prawn Noodle Soup', category: 'hawker', serving: '1 bowl', servingG: 450, calories: 480, proteinG: 25, carbsG: 55, fatG: 15, sodiumMg: 1450, sugarG: 3, fiberG: 2 },
  { key: 'claypot-rice', name: 'Claypot Rice', category: 'hawker', serving: '1 serving', servingG: 400, calories: 650, proteinG: 28, carbsG: 85, fatG: 20, sodiumMg: 1100, sugarG: 3, fiberG: 2 },
  { key: 'mee-siam', name: 'Mee Siam', category: 'hawker', serving: '1 plate', servingG: 350, calories: 450, proteinG: 12, carbsG: 65, fatG: 15, sodiumMg: 950, sugarG: 10, fiberG: 2 },
  { key: 'otah', name: 'Otah (grilled fish cake)', category: 'hawker', serving: '2 pieces', servingG: 100, calories: 180, proteinG: 12, carbsG: 6, fatG: 12, sodiumMg: 480, sugarG: 2, fiberG: 0.5 },
  { key: 'sushi-salmon-nigiri', name: 'Salmon Nigiri Sushi', category: 'japanese', serving: '2 pieces', servingG: 60, calories: 90, proteinG: 6, carbsG: 14, fatG: 1.5, sodiumMg: 200, sugarG: 2, fiberG: 0 },
  { key: 'sushi-tuna-nigiri', name: 'Tuna Nigiri Sushi', category: 'japanese', serving: '2 pieces', servingG: 60, calories: 85, proteinG: 7, carbsG: 13, fatG: 0.5, sodiumMg: 190, sugarG: 2, fiberG: 0 },
  { key: 'sushi-california-roll', name: 'California Roll', category: 'japanese', serving: '6 pieces', servingG: 170, calories: 260, proteinG: 7, carbsG: 38, fatG: 8, sodiumMg: 480, sugarG: 6, fiberG: 2 },
  { key: 'sashimi-salmon', name: 'Salmon Sashimi', category: 'japanese', serving: '5 slices', servingG: 100, calories: 180, proteinG: 20, carbsG: 0, fatG: 11, sodiumMg: 45, sugarG: 0, fiberG: 0 },
  { key: 'sashimi-tuna', name: 'Tuna Sashimi', category: 'japanese', serving: '5 slices', servingG: 100, calories: 140, proteinG: 24, carbsG: 0, fatG: 4, sodiumMg: 40, sugarG: 0, fiberG: 0 },
  { key: 'ramen-shoyu-chicken', name: 'Chicken Shoyu Ramen', category: 'japanese', serving: '1 bowl', servingG: 600, calories: 550, proteinG: 25, carbsG: 65, fatG: 18, sodiumMg: 1900, sugarG: 3, fiberG: 3 },
  { key: 'ramen-tonkotsu', name: 'Tonkotsu Ramen', category: 'japanese', serving: '1 bowl', servingG: 650, calories: 680, proteinG: 28, carbsG: 60, fatG: 34, sodiumMg: 2000, sugarG: 3, fiberG: 2 },
  { key: 'ramen-miso', name: 'Miso Ramen', category: 'japanese', serving: '1 bowl', servingG: 600, calories: 600, proteinG: 24, carbsG: 68, fatG: 22, sodiumMg: 1850, sugarG: 4, fiberG: 3 },
  { key: 'instant-ramen-cup', name: 'Instant Cup Ramen', category: 'japanese', serving: '1 cup', servingG: 70, calories: 380, proteinG: 8, carbsG: 52, fatG: 16, sodiumMg: 1700, sugarG: 3, fiberG: 2 },
  { key: 'yakitori-chicken-skin', name: 'Yakitori (chicken skin)', category: 'japanese', serving: '2 sticks', servingG: 80, calories: 200, proteinG: 12, carbsG: 4, fatG: 15, sodiumMg: 350, sugarG: 2, fiberG: 0 },
  { key: 'yakitori-negima', name: 'Yakitori (chicken thigh & leek)', category: 'japanese', serving: '2 sticks', servingG: 100, calories: 180, proteinG: 20, carbsG: 5, fatG: 8, sodiumMg: 400, sugarG: 3, fiberG: 0 },
  { key: 'karaage', name: 'Chicken Karaage', category: 'japanese', serving: '5 pieces', servingG: 150, calories: 380, proteinG: 22, carbsG: 18, fatG: 24, sodiumMg: 650, sugarG: 2, fiberG: 1 },
  { key: 'edamame', name: 'Edamame (steamed, salted)', category: 'japanese', serving: '1 bowl', servingG: 150, calories: 120, proteinG: 11, carbsG: 10, fatG: 5, sodiumMg: 300, sugarG: 2, fiberG: 5 },
  { key: 'unagi-don', name: 'Unagi Don (grilled eel rice bowl)', category: 'japanese', serving: '1 bowl', servingG: 350, calories: 620, proteinG: 28, carbsG: 80, fatG: 20, sodiumMg: 900, sugarG: 15, fiberG: 1 },
  { key: 'wagyu-don', name: 'Wagyu Beef Don', category: 'japanese', serving: '1 bowl', servingG: 350, calories: 750, proteinG: 30, carbsG: 70, fatG: 38, sodiumMg: 750, sugarG: 6, fiberG: 1 },
  { key: 'gyudon', name: 'Gyudon (beef rice bowl)', category: 'japanese', serving: '1 bowl', servingG: 400, calories: 650, proteinG: 25, carbsG: 85, fatG: 22, sodiumMg: 950, sugarG: 10, fiberG: 1 },
  { key: 'tempura-prawn', name: 'Prawn Tempura', category: 'japanese', serving: '4 pieces', servingG: 150, calories: 320, proteinG: 14, carbsG: 28, fatG: 18, sodiumMg: 500, sugarG: 1, fiberG: 1 },
  { key: 'tempura-vegetable', name: 'Vegetable Tempura', category: 'japanese', serving: '6 pieces', servingG: 150, calories: 280, proteinG: 5, carbsG: 32, fatG: 15, sodiumMg: 400, sugarG: 2, fiberG: 3 },
  { key: 'takoyaki', name: 'Takoyaki', category: 'japanese', serving: '6 pieces', servingG: 180, calories: 380, proteinG: 12, carbsG: 40, fatG: 18, sodiumMg: 700, sugarG: 5, fiberG: 1 },
  { key: 'gyoza', name: 'Gyoza (pan-fried dumplings)', category: 'japanese', serving: '6 pieces', servingG: 150, calories: 300, proteinG: 12, carbsG: 30, fatG: 15, sodiumMg: 650, sugarG: 2, fiberG: 2 },
  { key: 'agedashi-tofu', name: 'Agedashi Tofu', category: 'japanese', serving: '1 serving', servingG: 150, calories: 220, proteinG: 10, carbsG: 15, fatG: 14, sodiumMg: 550, sugarG: 2, fiberG: 1 },
  { key: 'chawanmushi', name: 'Chawanmushi (savoury egg custard)', category: 'japanese', serving: '1 cup', servingG: 120, calories: 90, proteinG: 7, carbsG: 4, fatG: 5, sodiumMg: 350, sugarG: 1, fiberG: 0 },
  { key: 'miso-soup', name: 'Miso Soup', category: 'japanese', serving: '1 bowl', servingG: 250, calories: 60, proteinG: 4, carbsG: 5, fatG: 2, sodiumMg: 900, sugarG: 1, fiberG: 1 },
  { key: 'okonomiyaki', name: 'Okonomiyaki', category: 'japanese', serving: '1 serving', servingG: 300, calories: 550, proteinG: 18, carbsG: 45, fatG: 32, sodiumMg: 1100, sugarG: 6, fiberG: 2 },
  { key: 'katsu-curry-chicken', name: 'Chicken Katsu Curry', category: 'japanese', serving: '1 plate', servingG: 450, calories: 780, proteinG: 30, carbsG: 95, fatG: 30, sodiumMg: 1200, sugarG: 8, fiberG: 3 },
  { key: 'tonkatsu', name: 'Tonkatsu (pork cutlet)', category: 'japanese', serving: '1 serving', servingG: 200, calories: 480, proteinG: 25, carbsG: 25, fatG: 30, sodiumMg: 550, sugarG: 2, fiberG: 1 },
  { key: 'chicken-teriyaki', name: 'Chicken Teriyaki', category: 'japanese', serving: '1 serving', servingG: 200, calories: 350, proteinG: 30, carbsG: 20, fatG: 15, sodiumMg: 900, sugarG: 14, fiberG: 0 },
  { key: 'beef-yakiniku', name: 'Beef Yakiniku', category: 'japanese', serving: '1 serving', servingG: 150, calories: 400, proteinG: 25, carbsG: 8, fatG: 30, sodiumMg: 550, sugarG: 4, fiberG: 0 },
  { key: 'onigiri-salmon', name: 'Salmon Onigiri', category: 'japanese', serving: '1 piece', servingG: 100, calories: 180, proteinG: 5, carbsG: 35, fatG: 2, sodiumMg: 350, sugarG: 1, fiberG: 1 },
  { key: 'natto', name: 'Natto (fermented soybeans)', category: 'japanese', serving: '1 pack', servingG: 50, calories: 100, proteinG: 8, carbsG: 6, fatG: 5, sodiumMg: 5, sugarG: 1, fiberG: 3 },
  { key: 'har-gow', name: 'Har Gow (prawn dumplings)', category: 'chinese', serving: '4 pieces', servingG: 120, calories: 180, proteinG: 10, carbsG: 22, fatG: 6, sodiumMg: 400, sugarG: 1, fiberG: 1 },
  { key: 'siu-mai', name: 'Siu Mai (pork dumplings)', category: 'chinese', serving: '4 pieces', servingG: 120, calories: 220, proteinG: 12, carbsG: 15, fatG: 12, sodiumMg: 500, sugarG: 1, fiberG: 1 },
  { key: 'char-siu-bao', name: 'Char Siu Bao (BBQ pork bun)', category: 'chinese', serving: '1 bun', servingG: 100, calories: 250, proteinG: 8, carbsG: 40, fatG: 7, sodiumMg: 400, sugarG: 10, fiberG: 1 },
  { key: 'spring-roll-chinese', name: 'Chinese Spring Rolls', category: 'chinese', serving: '2 rolls', servingG: 100, calories: 220, proteinG: 5, carbsG: 25, fatG: 11, sodiumMg: 350, sugarG: 2, fiberG: 1 },
  { key: 'congee-plain', name: 'Plain Congee', category: 'chinese', serving: '1 bowl', servingG: 350, calories: 180, proteinG: 4, carbsG: 38, fatG: 1, sodiumMg: 300, sugarG: 0, fiberG: 1 },
  { key: 'century-egg-congee', name: 'Century Egg & Pork Congee', category: 'chinese', serving: '1 bowl', servingG: 400, calories: 280, proteinG: 10, carbsG: 40, fatG: 8, sodiumMg: 750, sugarG: 1, fiberG: 1 },
  { key: 'fried-rice-yangzhou', name: 'Yangzhou Fried Rice', category: 'chinese', serving: '1 plate', servingG: 350, calories: 620, proteinG: 18, carbsG: 75, fatG: 25, sodiumMg: 1000, sugarG: 3, fiberG: 2 },
  { key: 'sweet-sour-pork', name: 'Sweet and Sour Pork', category: 'chinese', serving: '1 serving', servingG: 250, calories: 550, proteinG: 22, carbsG: 55, fatG: 28, sodiumMg: 800, sugarG: 20, fiberG: 1 },
  { key: 'kung-pao-chicken', name: 'Kung Pao Chicken', category: 'chinese', serving: '1 serving', servingG: 250, calories: 420, proteinG: 28, carbsG: 20, fatG: 25, sodiumMg: 950, sugarG: 8, fiberG: 2 },
  { key: 'mapo-tofu', name: 'Mapo Tofu', category: 'chinese', serving: '1 serving', servingG: 250, calories: 380, proteinG: 18, carbsG: 12, fatG: 28, sodiumMg: 1100, sugarG: 3, fiberG: 2 },
  { key: 'peking-duck-pancakes', name: 'Peking Duck with Pancakes', category: 'chinese', serving: '2 pancakes', servingG: 150, calories: 380, proteinG: 15, carbsG: 30, fatG: 22, sodiumMg: 650, sugarG: 5, fiberG: 1 },
  { key: 'wonton-soup', name: 'Wonton Soup', category: 'chinese', serving: '1 bowl', servingG: 350, calories: 280, proteinG: 14, carbsG: 30, fatG: 10, sodiumMg: 1200, sugarG: 2, fiberG: 1 },
  { key: 'xiao-long-bao', name: 'Xiao Long Bao (soup dumplings)', category: 'chinese', serving: '4 pieces', servingG: 120, calories: 220, proteinG: 9, carbsG: 25, fatG: 9, sodiumMg: 450, sugarG: 1, fiberG: 1 },
  { key: 'hor-fun-wet', name: 'Wet Hor Fun (fried flat noodles)', category: 'chinese', serving: '1 plate', servingG: 400, calories: 580, proteinG: 22, carbsG: 65, fatG: 22, sodiumMg: 1300, sugarG: 3, fiberG: 2 },
  { key: 'steamed-fish-hongkong', name: 'Steamed Fish, Hong Kong Style', category: 'chinese', serving: '1 serving', servingG: 250, calories: 280, proteinG: 35, carbsG: 6, fatG: 12, sodiumMg: 800, sugarG: 3, fiberG: 0 },
  { key: 'cheeseburger', name: 'Cheeseburger', category: 'western', serving: '1 burger', servingG: 220, calories: 550, proteinG: 28, carbsG: 40, fatG: 30, sodiumMg: 1000, sugarG: 8, fiberG: 2 },
  { key: 'beef-burger-plain', name: 'Beef Burger (plain)', category: 'western', serving: '1 burger', servingG: 200, calories: 480, proteinG: 25, carbsG: 38, fatG: 24, sodiumMg: 750, sugarG: 6, fiberG: 2 },
  { key: 'chicken-caesar-salad', name: 'Chicken Caesar Salad', category: 'western', serving: '1 bowl', servingG: 350, calories: 450, proteinG: 32, carbsG: 15, fatG: 28, sodiumMg: 900, sugarG: 4, fiberG: 3 },
  { key: 'spaghetti-bolognese', name: 'Spaghetti Bolognese', category: 'western', serving: '1 plate', servingG: 400, calories: 600, proteinG: 25, carbsG: 75, fatG: 20, sodiumMg: 850, sugarG: 10, fiberG: 4 },
  { key: 'carbonara', name: 'Spaghetti Carbonara', category: 'western', serving: '1 plate', servingG: 380, calories: 700, proteinG: 25, carbsG: 65, fatG: 38, sodiumMg: 900, sugarG: 3, fiberG: 2 },
  { key: 'margherita-pizza-slice', name: 'Margherita Pizza (slice)', category: 'western', serving: '1 slice', servingG: 130, calories: 280, proteinG: 12, carbsG: 33, fatG: 11, sodiumMg: 550, sugarG: 3, fiberG: 2 },
  { key: 'pepperoni-pizza-slice', name: 'Pepperoni Pizza (slice)', category: 'western', serving: '1 slice', servingG: 140, calories: 330, proteinG: 14, carbsG: 32, fatG: 17, sodiumMg: 700, sugarG: 3, fiberG: 2 },
  { key: 'fish-and-chips', name: 'Fish and Chips', category: 'western', serving: '1 serving', servingG: 350, calories: 800, proteinG: 30, carbsG: 70, fatG: 45, sodiumMg: 1100, sugarG: 2, fiberG: 4 },
  { key: 'steak-sirloin', name: 'Sirloin Steak (grilled)', category: 'western', serving: '1 steak', servingG: 200, calories: 480, proteinG: 48, carbsG: 0, fatG: 32, sodiumMg: 350, sugarG: 0, fiberG: 0 },
  { key: 'mashed-potato', name: 'Mashed Potato', category: 'western', serving: '1 cup', servingG: 200, calories: 220, proteinG: 4, carbsG: 35, fatG: 8, sodiumMg: 450, sugarG: 3, fiberG: 3 },
  { key: 'french-fries', name: 'French Fries', category: 'western', serving: '1 medium', servingG: 150, calories: 450, proteinG: 5, carbsG: 55, fatG: 22, sodiumMg: 400, sugarG: 0, fiberG: 4 },
  { key: 'mac-and-cheese', name: 'Mac and Cheese', category: 'western', serving: '1 bowl', servingG: 300, calories: 550, proteinG: 20, carbsG: 55, fatG: 28, sodiumMg: 950, sugarG: 6, fiberG: 2 },
  { key: 'club-sandwich', name: 'Club Sandwich', category: 'western', serving: '1 sandwich', servingG: 300, calories: 550, proteinG: 30, carbsG: 45, fatG: 28, sodiumMg: 1100, sugarG: 5, fiberG: 3 },
  { key: 'bacon-egg-sandwich', name: 'Bacon & Egg Sandwich', category: 'western', serving: '1 sandwich', servingG: 200, calories: 450, proteinG: 22, carbsG: 35, fatG: 25, sodiumMg: 900, sugarG: 3, fiberG: 2 },
  { key: 'caesar-wrap', name: 'Chicken Caesar Wrap', category: 'western', serving: '1 wrap', servingG: 250, calories: 480, proteinG: 25, carbsG: 40, fatG: 24, sodiumMg: 950, sugarG: 3, fiberG: 3 },
  { key: 'roast-beef-dinner', name: 'Roast Beef Dinner', category: 'western', serving: '1 plate', servingG: 400, calories: 600, proteinG: 40, carbsG: 45, fatG: 28, sodiumMg: 700, sugarG: 5, fiberG: 4 },
  { key: 'mushroom-soup', name: 'Cream of Mushroom Soup', category: 'western', serving: '1 bowl', servingG: 300, calories: 220, proteinG: 5, carbsG: 18, fatG: 14, sodiumMg: 850, sugarG: 4, fiberG: 1 },
  { key: 'clam-chowder', name: 'Clam Chowder', category: 'western', serving: '1 bowl', servingG: 300, calories: 280, proteinG: 12, carbsG: 22, fatG: 16, sodiumMg: 950, sugarG: 3, fiberG: 1 },
  { key: 'lasagna', name: 'Lasagna', category: 'western', serving: '1 slice', servingG: 300, calories: 480, proteinG: 25, carbsG: 40, fatG: 24, sodiumMg: 850, sugarG: 6, fiberG: 3 },
  { key: 'grilled-cheese-sandwich', name: 'Grilled Cheese Sandwich', category: 'western', serving: '1 sandwich', servingG: 150, calories: 400, proteinG: 15, carbsG: 32, fatG: 24, sodiumMg: 750, sugarG: 4, fiberG: 1 },
  { key: 'kaya-toast-set', name: 'Kaya Toast Set (toast + egg)', category: 'breakfast', serving: '1 set', servingG: 150, calories: 380, proteinG: 10, carbsG: 45, fatG: 18, sodiumMg: 500, sugarG: 20, fiberG: 1 },
  { key: 'soft-boiled-eggs', name: 'Soft-Boiled Eggs', category: 'breakfast', serving: '2 eggs', servingG: 100, calories: 140, proteinG: 12, carbsG: 1, fatG: 10, sodiumMg: 140, sugarG: 0, fiberG: 0 },
  { key: 'plain-oatmeal', name: 'Plain Oatmeal (cooked)', category: 'breakfast', serving: '1 bowl', servingG: 250, calories: 150, proteinG: 5, carbsG: 27, fatG: 3, sodiumMg: 5, sugarG: 1, fiberG: 4 },
  { key: 'scrambled-eggs', name: 'Scrambled Eggs', category: 'breakfast', serving: '2 eggs', servingG: 120, calories: 200, proteinG: 13, carbsG: 2, fatG: 16, sodiumMg: 200, sugarG: 1, fiberG: 0 },
  { key: 'pancakes-stack', name: 'Pancakes (stack of 3, no syrup)', category: 'breakfast', serving: '3 pancakes', servingG: 150, calories: 350, proteinG: 8, carbsG: 55, fatG: 10, sodiumMg: 500, sugarG: 15, fiberG: 2 },
  { key: 'waffles', name: 'Waffles', category: 'breakfast', serving: '2 waffles', servingG: 140, calories: 380, proteinG: 8, carbsG: 50, fatG: 16, sodiumMg: 550, sugarG: 10, fiberG: 2 },
  { key: 'cereal-cornflakes', name: 'Cornflakes with Milk', category: 'breakfast', serving: '1 bowl', servingG: 250, calories: 200, proteinG: 6, carbsG: 40, fatG: 2, sodiumMg: 250, sugarG: 12, fiberG: 2 },
  { key: 'muesli', name: 'Muesli with Milk', category: 'breakfast', serving: '1 bowl', servingG: 260, calories: 280, proteinG: 10, carbsG: 45, fatG: 7, sodiumMg: 100, sugarG: 15, fiberG: 5 },
  { key: 'french-toast', name: 'French Toast', category: 'breakfast', serving: '2 slices', servingG: 150, calories: 380, proteinG: 10, carbsG: 45, fatG: 17, sodiumMg: 400, sugarG: 12, fiberG: 2 },
  { key: 'bagel-cream-cheese', name: 'Bagel with Cream Cheese', category: 'breakfast', serving: '1 bagel', servingG: 130, calories: 380, proteinG: 12, carbsG: 55, fatG: 13, sodiumMg: 600, sugarG: 6, fiberG: 2 },
  { key: 'croissant-plain', name: 'Croissant (plain)', category: 'breakfast', serving: '1 piece', servingG: 70, calories: 280, proteinG: 6, carbsG: 30, fatG: 15, sodiumMg: 350, sugarG: 5, fiberG: 1 },
  { key: 'yogurt-parfait', name: 'Yogurt Parfait (granola & fruit)', category: 'breakfast', serving: '1 cup', servingG: 200, calories: 250, proteinG: 10, carbsG: 35, fatG: 8, sodiumMg: 100, sugarG: 25, fiberG: 2 },
  { key: 'grilled-chicken-breast', name: 'Grilled Chicken Breast (skinless)', category: 'proteins', serving: '1 breast', servingG: 150, calories: 250, proteinG: 45, carbsG: 0, fatG: 6, sodiumMg: 300, sugarG: 0, fiberG: 0 },
  { key: 'salmon-fillet-grilled', name: 'Grilled Salmon Fillet', category: 'proteins', serving: '1 fillet', servingG: 150, calories: 310, proteinG: 34, carbsG: 0, fatG: 18, sodiumMg: 90, sugarG: 0, fiberG: 0 },
  { key: 'tofu-firm', name: 'Firm Tofu', category: 'proteins', serving: '100 g', servingG: 100, calories: 145, proteinG: 15, carbsG: 3, fatG: 9, sodiumMg: 10, sugarG: 1, fiberG: 2 },
  { key: 'egg-whole-boiled', name: 'Boiled Egg', category: 'proteins', serving: '1 egg', servingG: 50, calories: 78, proteinG: 6, carbsG: 0.5, fatG: 5, sodiumMg: 70, sugarG: 0, fiberG: 0 },
  { key: 'tuna-canned-water', name: 'Canned Tuna (in water, drained)', category: 'proteins', serving: '1 can', servingG: 100, calories: 110, proteinG: 25, carbsG: 0, fatG: 1, sodiumMg: 300, sugarG: 0, fiberG: 0 },
  { key: 'lean-beef-mince-cooked', name: 'Lean Beef Mince (cooked)', category: 'proteins', serving: '100 g', servingG: 100, calories: 215, proteinG: 26, carbsG: 0, fatG: 12, sodiumMg: 75, sugarG: 0, fiberG: 0 },
  { key: 'pork-chop-grilled', name: 'Grilled Pork Chop', category: 'proteins', serving: '1 chop', servingG: 150, calories: 320, proteinG: 38, carbsG: 0, fatG: 18, sodiumMg: 300, sugarG: 0, fiberG: 0 },
  { key: 'shrimp-cooked', name: 'Cooked Shrimp/Prawns', category: 'proteins', serving: '100 g', servingG: 100, calories: 99, proteinG: 21, carbsG: 0, fatG: 1, sodiumMg: 190, sugarG: 0, fiberG: 0 },
  { key: 'tempeh', name: 'Tempeh', category: 'proteins', serving: '100 g', servingG: 100, calories: 190, proteinG: 19, carbsG: 9, fatG: 11, sodiumMg: 10, sugarG: 0, fiberG: 5 },
  { key: 'greek-yogurt-plain', name: 'Greek Yogurt (plain, non-fat)', category: 'proteins', serving: '1 cup', servingG: 170, calories: 100, proteinG: 17, carbsG: 6, fatG: 0.5, sodiumMg: 60, sugarG: 6, fiberG: 0 },
  { key: 'cottage-cheese', name: 'Cottage Cheese', category: 'proteins', serving: '100 g', servingG: 100, calories: 98, proteinG: 11, carbsG: 3, fatG: 4, sodiumMg: 350, sugarG: 3, fiberG: 0 },
  { key: 'chicken-thigh-grilled', name: 'Grilled Chicken Thigh (skin-on)', category: 'proteins', serving: '1 thigh', servingG: 150, calories: 280, proteinG: 30, carbsG: 0, fatG: 17, sodiumMg: 250, sugarG: 0, fiberG: 0 },
  { key: 'duck-breast-grilled', name: 'Grilled Duck Breast', category: 'proteins', serving: '1 breast', servingG: 150, calories: 340, proteinG: 32, carbsG: 0, fatG: 22, sodiumMg: 200, sugarG: 0, fiberG: 0 },
  { key: 'lentils-cooked', name: 'Cooked Lentils', category: 'proteins', serving: '1 cup', servingG: 200, calories: 230, proteinG: 18, carbsG: 40, fatG: 1, sodiumMg: 5, sugarG: 2, fiberG: 16 },
  { key: 'chickpeas-cooked', name: 'Cooked Chickpeas', category: 'proteins', serving: '1 cup', servingG: 200, calories: 270, proteinG: 15, carbsG: 45, fatG: 4, sodiumMg: 12, sugarG: 8, fiberG: 13 },
  { key: 'apple', name: 'Apple (medium)', category: 'fruits', serving: '1 medium', servingG: 180, calories: 95, proteinG: 0.5, carbsG: 25, fatG: 0.3, sodiumMg: 2, sugarG: 19, fiberG: 4 },
  { key: 'banana', name: 'Banana (medium)', category: 'fruits', serving: '1 medium', servingG: 120, calories: 105, proteinG: 1.3, carbsG: 27, fatG: 0.4, sodiumMg: 1, sugarG: 14, fiberG: 3 },
  { key: 'orange', name: 'Orange (medium)', category: 'fruits', serving: '1 medium', servingG: 150, calories: 70, proteinG: 1.3, carbsG: 17, fatG: 0.2, sodiumMg: 0, sugarG: 12, fiberG: 3 },
  { key: 'watermelon', name: 'Watermelon (cubed)', category: 'fruits', serving: '1 cup', servingG: 150, calories: 45, proteinG: 1, carbsG: 11, fatG: 0.2, sodiumMg: 2, sugarG: 9, fiberG: 0.5 },
  { key: 'papaya', name: 'Papaya (cubed)', category: 'fruits', serving: '1 cup', servingG: 150, calories: 60, proteinG: 1, carbsG: 15, fatG: 0.2, sodiumMg: 5, sugarG: 11, fiberG: 3 },
  { key: 'pineapple', name: 'Pineapple (cubed)', category: 'fruits', serving: '1 cup', servingG: 165, calories: 82, proteinG: 0.9, carbsG: 22, fatG: 0.2, sodiumMg: 2, sugarG: 16, fiberG: 2 },
  { key: 'mango', name: 'Mango (sliced)', category: 'fruits', serving: '1 cup', servingG: 165, calories: 100, proteinG: 1.4, carbsG: 25, fatG: 0.6, sodiumMg: 2, sugarG: 23, fiberG: 3 },
  { key: 'grapes', name: 'Grapes', category: 'fruits', serving: '1 cup', servingG: 150, calories: 100, proteinG: 1, carbsG: 27, fatG: 0.3, sodiumMg: 3, sugarG: 23, fiberG: 1 },
  { key: 'strawberries', name: 'Strawberries', category: 'fruits', serving: '1 cup', servingG: 150, calories: 48, proteinG: 1, carbsG: 11, fatG: 0.5, sodiumMg: 2, sugarG: 7, fiberG: 3 },
  { key: 'dragon-fruit', name: 'Dragon Fruit (cubed)', category: 'fruits', serving: '1 cup', servingG: 150, calories: 85, proteinG: 1.5, carbsG: 20, fatG: 0.5, sodiumMg: 0, sugarG: 13, fiberG: 4 },
  { key: 'rambutan', name: 'Rambutan', category: 'fruits', serving: '6 pieces', servingG: 100, calories: 75, proteinG: 0.9, carbsG: 18, fatG: 0.2, sodiumMg: 5, sugarG: 15, fiberG: 1 },
  { key: 'durian', name: 'Durian', category: 'fruits', serving: '100 g', servingG: 100, calories: 147, proteinG: 1.5, carbsG: 27, fatG: 5, sodiumMg: 2, sugarG: 21, fiberG: 4 },
  { key: 'guava', name: 'Guava (medium)', category: 'fruits', serving: '1 medium', servingG: 150, calories: 75, proteinG: 2.7, carbsG: 18, fatG: 1, sodiumMg: 3, sugarG: 12, fiberG: 7 },
  { key: 'kiwi', name: 'Kiwi Fruit (medium)', category: 'fruits', serving: '1 medium', servingG: 75, calories: 45, proteinG: 0.8, carbsG: 11, fatG: 0.4, sodiumMg: 2, sugarG: 7, fiberG: 2 },
  { key: 'avocado-half', name: 'Avocado (half)', category: 'fruits', serving: 'half', servingG: 100, calories: 160, proteinG: 2, carbsG: 9, fatG: 15, sodiumMg: 7, sugarG: 0.7, fiberG: 7 },
  { key: 'broccoli-steamed', name: 'Steamed Broccoli', category: 'vegetables', serving: '1 cup', servingG: 150, calories: 55, proteinG: 4, carbsG: 11, fatG: 0.5, sodiumMg: 55, sugarG: 2, fiberG: 5 },
  { key: 'spinach-cooked', name: 'Cooked Spinach', category: 'vegetables', serving: '1 cup', servingG: 180, calories: 40, proteinG: 5, carbsG: 7, fatG: 0.5, sodiumMg: 130, sugarG: 1, fiberG: 4 },
  { key: 'kailan-stir-fried', name: 'Stir-Fried Kailan (with oyster sauce)', category: 'vegetables', serving: '1 plate', servingG: 150, calories: 120, proteinG: 4, carbsG: 8, fatG: 8, sodiumMg: 450, sugarG: 2, fiberG: 3 },
  { key: 'sambal-kangkong', name: 'Sambal Kangkong (water spinach)', category: 'vegetables', serving: '1 plate', servingG: 150, calories: 150, proteinG: 4, carbsG: 10, fatG: 10, sodiumMg: 550, sugarG: 2, fiberG: 3 },
  { key: 'carrot-raw', name: 'Carrot (raw, medium)', category: 'vegetables', serving: '1 medium', servingG: 60, calories: 25, proteinG: 0.6, carbsG: 6, fatG: 0.1, sodiumMg: 40, sugarG: 3, fiberG: 2 },
  { key: 'cucumber-slices', name: 'Cucumber Slices', category: 'vegetables', serving: '1 cup', servingG: 100, calories: 15, proteinG: 0.6, carbsG: 3.6, fatG: 0.1, sodiumMg: 2, sugarG: 2, fiberG: 0.5 },
  { key: 'tomato', name: 'Tomato (medium)', category: 'vegetables', serving: '1 medium', servingG: 120, calories: 22, proteinG: 1.1, carbsG: 5, fatG: 0.2, sodiumMg: 6, sugarG: 3, fiberG: 1.5 },
  { key: 'sweet-potato-baked', name: 'Baked Sweet Potato', category: 'vegetables', serving: '1 medium', servingG: 150, calories: 130, proteinG: 2.3, carbsG: 30, fatG: 0.2, sodiumMg: 55, sugarG: 6, fiberG: 4 },
  { key: 'corn-on-cob', name: 'Corn on the Cob', category: 'vegetables', serving: '1 medium', servingG: 150, calories: 140, proteinG: 4.5, carbsG: 30, fatG: 1.5, sodiumMg: 20, sugarG: 6, fiberG: 3 },
  { key: 'bittergourd-stir-fry', name: 'Stir-Fried Bitter Gourd', category: 'vegetables', serving: '1 plate', servingG: 150, calories: 110, proteinG: 3, carbsG: 8, fatG: 7, sodiumMg: 450, sugarG: 2, fiberG: 3 },
  { key: 'mixed-salad-greens', name: 'Mixed Salad Greens (no dressing)', category: 'vegetables', serving: '1 bowl', servingG: 100, calories: 25, proteinG: 2, carbsG: 4, fatG: 0.3, sodiumMg: 20, sugarG: 2, fiberG: 2 },
  { key: 'mushroom-stir-fried', name: 'Stir-Fried Mushrooms', category: 'vegetables', serving: '1 cup', servingG: 150, calories: 110, proteinG: 3, carbsG: 6, fatG: 8, sodiumMg: 400, sugarG: 2, fiberG: 2 },
  { key: 'potato-chips', name: 'Potato Chips', category: 'snacks', serving: '1 small bag', servingG: 30, calories: 160, proteinG: 2, carbsG: 15, fatG: 10, sodiumMg: 180, sugarG: 0.2, fiberG: 1 },
  { key: 'prawn-crackers', name: 'Prawn Crackers', category: 'snacks', serving: '1 small bag', servingG: 30, calories: 150, proteinG: 1, carbsG: 18, fatG: 8, sodiumMg: 300, sugarG: 1, fiberG: 0.5 },
  { key: 'peanuts-roasted', name: 'Roasted Peanuts', category: 'snacks', serving: '1/4 cup', servingG: 35, calories: 200, proteinG: 9, carbsG: 6, fatG: 17, sodiumMg: 120, sugarG: 1, fiberG: 3 },
  { key: 'mixed-nuts', name: 'Mixed Nuts', category: 'snacks', serving: '30 g', servingG: 30, calories: 180, proteinG: 6, carbsG: 7, fatG: 16, sodiumMg: 90, sugarG: 1, fiberG: 2.5 },
  { key: 'chocolate-bar', name: 'Chocolate Bar', category: 'snacks', serving: '1 bar', servingG: 45, calories: 240, proteinG: 3, carbsG: 27, fatG: 13, sodiumMg: 40, sugarG: 24, fiberG: 2 },
  { key: 'tortilla-chips', name: 'Tortilla Chips', category: 'snacks', serving: '1 small bag', servingG: 30, calories: 150, proteinG: 2, carbsG: 18, fatG: 8, sodiumMg: 200, sugarG: 1, fiberG: 1 },
  { key: 'rice-crackers', name: 'Rice Crackers', category: 'snacks', serving: '1 pack', servingG: 30, calories: 120, proteinG: 2, carbsG: 24, fatG: 2, sodiumMg: 350, sugarG: 1, fiberG: 1 },
  { key: 'dried-seaweed-snack', name: 'Dried Seaweed Snack', category: 'snacks', serving: '1 pack', servingG: 5, calories: 20, proteinG: 1, carbsG: 1, fatG: 1.5, sodiumMg: 150, sugarG: 0, fiberG: 0.5 },
  { key: 'keropok-lekor', name: 'Keropok Lekor (fish crackers)', category: 'snacks', serving: '5 pieces', servingG: 100, calories: 250, proteinG: 10, carbsG: 30, fatG: 10, sodiumMg: 550, sugarG: 2, fiberG: 1 },
  { key: 'curry-puff', name: 'Curry Puff', category: 'snacks', serving: '1 piece', servingG: 80, calories: 220, proteinG: 5, carbsG: 22, fatG: 13, sodiumMg: 350, sugarG: 2, fiberG: 1 },
  { key: 'egg-tart', name: 'Egg Tart', category: 'snacks', serving: '1 piece', servingG: 70, calories: 220, proteinG: 4, carbsG: 22, fatG: 13, sodiumMg: 120, sugarG: 12, fiberG: 0.5 },
  { key: 'muffin-blueberry', name: 'Blueberry Muffin', category: 'snacks', serving: '1 muffin', servingG: 110, calories: 350, proteinG: 5, carbsG: 50, fatG: 14, sodiumMg: 350, sugarG: 25, fiberG: 2 },
  { key: 'granola-bar', name: 'Granola Bar', category: 'snacks', serving: '1 bar', servingG: 35, calories: 150, proteinG: 3, carbsG: 22, fatG: 6, sodiumMg: 90, sugarG: 10, fiberG: 2 },
  { key: 'popcorn-salted', name: 'Salted Popcorn', category: 'snacks', serving: '1 cup', servingG: 20, calories: 100, proteinG: 2, carbsG: 12, fatG: 6, sodiumMg: 200, sugarG: 0, fiberG: 2 },
  { key: 'ice-cream-scoop', name: 'Ice Cream (vanilla, scoop)', category: 'snacks', serving: '1 scoop', servingG: 65, calories: 140, proteinG: 2.5, carbsG: 17, fatG: 7, sodiumMg: 55, sugarG: 14, fiberG: 0.5 },
  { key: 'chendol', name: 'Chendol', category: 'desserts', serving: '1 bowl', servingG: 250, calories: 350, proteinG: 4, carbsG: 60, fatG: 12, sodiumMg: 60, sugarG: 40, fiberG: 2 },
  { key: 'ice-kacang', name: 'Ice Kacang', category: 'desserts', serving: '1 bowl', servingG: 300, calories: 300, proteinG: 3, carbsG: 65, fatG: 4, sodiumMg: 50, sugarG: 45, fiberG: 2 },
  { key: 'mochi', name: 'Mochi', category: 'desserts', serving: '2 pieces', servingG: 60, calories: 140, proteinG: 2, carbsG: 30, fatG: 1.5, sodiumMg: 10, sugarG: 12, fiberG: 1 },
  { key: 'tau-huay', name: 'Tau Huay (soybean pudding)', category: 'desserts', serving: '1 bowl', servingG: 250, calories: 150, proteinG: 6, carbsG: 25, fatG: 3, sodiumMg: 20, sugarG: 20, fiberG: 1 },
  { key: 'cheesecake-slice', name: 'Cheesecake (slice)', category: 'desserts', serving: '1 slice', servingG: 120, calories: 400, proteinG: 6, carbsG: 32, fatG: 28, sodiumMg: 300, sugarG: 24, fiberG: 1 },
  { key: 'chocolate-cake-slice', name: 'Chocolate Cake (slice)', category: 'desserts', serving: '1 slice', servingG: 100, calories: 370, proteinG: 5, carbsG: 50, fatG: 18, sodiumMg: 300, sugarG: 35, fiberG: 2 },
  { key: 'red-bean-soup', name: 'Red Bean Soup (dessert)', category: 'desserts', serving: '1 bowl', servingG: 250, calories: 220, proteinG: 8, carbsG: 45, fatG: 1, sodiumMg: 10, sugarG: 25, fiberG: 6 },
  { key: 'pandan-cake-slice', name: 'Pandan Cake (slice)', category: 'desserts', serving: '1 slice', servingG: 80, calories: 250, proteinG: 4, carbsG: 35, fatG: 10, sodiumMg: 200, sugarG: 20, fiberG: 1 },
  { key: 'tiramisu', name: 'Tiramisu (slice)', category: 'desserts', serving: '1 slice', servingG: 120, calories: 380, proteinG: 6, carbsG: 35, fatG: 22, sodiumMg: 120, sugarG: 22, fiberG: 1 },
  { key: 'dorayaki', name: 'Dorayaki', category: 'desserts', serving: '1 piece', servingG: 80, calories: 230, proteinG: 5, carbsG: 42, fatG: 4, sodiumMg: 150, sugarG: 22, fiberG: 1 },
  { key: 'kopi-o', name: 'Kopi O (black coffee, sugar)', category: 'drinks', serving: '1 cup', servingG: 200, calories: 60, proteinG: 0, carbsG: 15, fatG: 0, sodiumMg: 5, sugarG: 15, fiberG: 0 },
  { key: 'kopi-c', name: 'Kopi C (coffee, evaporated milk)', category: 'drinks', serving: '1 cup', servingG: 200, calories: 90, proteinG: 1, carbsG: 16, fatG: 3, sodiumMg: 30, sugarG: 14, fiberG: 0 },
  { key: 'kopi', name: 'Kopi (coffee, condensed milk)', category: 'drinks', serving: '1 cup', servingG: 200, calories: 120, proteinG: 2, carbsG: 20, fatG: 4, sodiumMg: 40, sugarG: 18, fiberG: 0 },
  { key: 'kopi-peng', name: 'Kopi Peng (iced coffee)', category: 'drinks', serving: '1 cup', servingG: 250, calories: 140, proteinG: 2, carbsG: 24, fatG: 4, sodiumMg: 40, sugarG: 22, fiberG: 0 },
  { key: 'teh-o', name: 'Teh O (black tea, sugar)', category: 'drinks', serving: '1 cup', servingG: 200, calories: 50, proteinG: 0, carbsG: 13, fatG: 0, sodiumMg: 5, sugarG: 13, fiberG: 0 },
  { key: 'teh-c', name: 'Teh C (tea, evaporated milk)', category: 'drinks', serving: '1 cup', servingG: 200, calories: 110, proteinG: 2, carbsG: 18, fatG: 4, sodiumMg: 35, sugarG: 16, fiberG: 0 },
  { key: 'teh-tarik', name: 'Teh Tarik', category: 'drinks', serving: '1 cup', servingG: 200, calories: 130, proteinG: 3, carbsG: 20, fatG: 4, sodiumMg: 45, sugarG: 18, fiberG: 0 },
  { key: 'bubble-tea-milk-tea', name: 'Bubble Milk Tea', category: 'drinks', serving: '1 cup', servingG: 500, calories: 350, proteinG: 3, carbsG: 75, fatG: 5, sodiumMg: 90, sugarG: 55, fiberG: 0 },
  { key: 'bubble-tea-brown-sugar', name: 'Brown Sugar Bubble Tea', category: 'drinks', serving: '1 cup', servingG: 500, calories: 420, proteinG: 3, carbsG: 90, fatG: 6, sodiumMg: 100, sugarG: 65, fiberG: 0 },
  { key: 'beer-lager-pint', name: 'Beer (lager, pint)', category: 'drinks', serving: '1 pint', servingG: 500, calories: 200, proteinG: 2, carbsG: 16, fatG: 0, sodiumMg: 15, sugarG: 0, fiberG: 0 },
  { key: 'beer-craft-ipa', name: 'Craft Beer (IPA, bottle)', category: 'drinks', serving: '1 bottle', servingG: 330, calories: 220, proteinG: 2, carbsG: 18, fatG: 0, sodiumMg: 15, sugarG: 0, fiberG: 0 },
  { key: 'sake-hot', name: 'Sake (hot)', category: 'drinks', serving: '1 cup', servingG: 180, calories: 195, proteinG: 0.5, carbsG: 7, fatG: 0, sodiumMg: 5, sugarG: 0, fiberG: 0 },
  { key: 'highball-whisky-soda', name: 'Whisky Highball', category: 'drinks', serving: '1 glass', servingG: 350, calories: 105, proteinG: 0, carbsG: 0, fatG: 0, sodiumMg: 10, sugarG: 0, fiberG: 0 },
  { key: 'red-wine-glass', name: 'Red Wine (glass)', category: 'drinks', serving: '1 glass', servingG: 150, calories: 125, proteinG: 0.1, carbsG: 4, fatG: 0, sodiumMg: 6, sugarG: 1, fiberG: 0 },
  { key: 'white-wine-glass', name: 'White Wine (glass)', category: 'drinks', serving: '1 glass', servingG: 150, calories: 120, proteinG: 0.1, carbsG: 3.5, fatG: 0, sodiumMg: 6, sugarG: 1, fiberG: 0 },
  { key: 'soft-drink-cola', name: 'Cola (can)', category: 'drinks', serving: '1 can', servingG: 330, calories: 140, proteinG: 0, carbsG: 35, fatG: 0, sodiumMg: 15, sugarG: 35, fiberG: 0 },
  { key: 'orange-juice', name: 'Orange Juice', category: 'drinks', serving: '1 cup', servingG: 250, calories: 110, proteinG: 2, carbsG: 26, fatG: 0.5, sodiumMg: 5, sugarG: 21, fiberG: 0.5 },
  { key: 'soy-milk-unsweetened', name: 'Soy Milk (unsweetened)', category: 'drinks', serving: '1 cup', servingG: 250, calories: 80, proteinG: 7, carbsG: 4, fatG: 4, sodiumMg: 90, sugarG: 1, fiberG: 1 },
  { key: 'soy-milk-sweetened', name: 'Soy Milk (sweetened)', category: 'drinks', serving: '1 cup', servingG: 250, calories: 130, proteinG: 6, carbsG: 18, fatG: 4, sodiumMg: 90, sugarG: 15, fiberG: 1 },
  { key: 'milo-hot', name: 'Milo (hot)', category: 'drinks', serving: '1 cup', servingG: 250, calories: 180, proteinG: 6, carbsG: 28, fatG: 5, sodiumMg: 120, sugarG: 22, fiberG: 1 },
  { key: 'milo-iced', name: 'Milo (iced)', category: 'drinks', serving: '1 cup', servingG: 300, calories: 220, proteinG: 6, carbsG: 36, fatG: 6, sodiumMg: 130, sugarG: 30, fiberG: 1 },
  { key: 'sugarcane-juice', name: 'Sugarcane Juice', category: 'drinks', serving: '1 cup', servingG: 300, calories: 180, proteinG: 0, carbsG: 45, fatG: 0, sodiumMg: 10, sugarG: 42, fiberG: 0 },
  { key: 'coconut-water', name: 'Coconut Water', category: 'drinks', serving: '1 cup', servingG: 250, calories: 60, proteinG: 2, carbsG: 14, fatG: 0, sodiumMg: 100, sugarG: 11, fiberG: 1 },
  { key: 'plain-water', name: 'Plain Water', category: 'drinks', serving: '1 cup', servingG: 250, calories: 0, proteinG: 0, carbsG: 0, fatG: 0, sodiumMg: 0, sugarG: 0, fiberG: 0 },
  { key: 'black-coffee', name: 'Black Coffee (no sugar)', category: 'drinks', serving: '1 cup', servingG: 200, calories: 5, proteinG: 0.3, carbsG: 0, fatG: 0, sodiumMg: 5, sugarG: 0, fiberG: 0 },
  { key: 'latte', name: 'Latte', category: 'drinks', serving: '1 cup', servingG: 250, calories: 150, proteinG: 8, carbsG: 12, fatG: 8, sodiumMg: 100, sugarG: 12, fiberG: 0 },
  { key: 'soy-sauce-light', name: 'Light Soy Sauce', category: 'condiments', serving: '1 tbsp', servingG: 15, calories: 10, proteinG: 1, carbsG: 1, fatG: 0, sodiumMg: 900, sugarG: 0, fiberG: 0 },
  { key: 'soy-sauce-dark', name: 'Dark Soy Sauce', category: 'condiments', serving: '1 tbsp', servingG: 15, calories: 15, proteinG: 1, carbsG: 3, fatG: 0, sodiumMg: 780, sugarG: 2, fiberG: 0 },
  { key: 'oyster-sauce', name: 'Oyster Sauce', category: 'condiments', serving: '1 tbsp', servingG: 15, calories: 25, proteinG: 0.5, carbsG: 5, fatG: 0.1, sodiumMg: 490, sugarG: 3, fiberG: 0 },
  { key: 'fish-sauce', name: 'Fish Sauce', category: 'condiments', serving: '1 tbsp', servingG: 15, calories: 10, proteinG: 1.5, carbsG: 0.6, fatG: 0, sodiumMg: 1400, sugarG: 0, fiberG: 0 },
  { key: 'chili-sauce-sriracha', name: 'Sriracha Chili Sauce', category: 'condiments', serving: '1 tbsp', servingG: 15, calories: 15, proteinG: 0.2, carbsG: 3.5, fatG: 0, sodiumMg: 230, sugarG: 2, fiberG: 0 },
  { key: 'sambal-belacan', name: 'Sambal Belacan', category: 'condiments', serving: '1 tbsp', servingG: 15, calories: 30, proteinG: 1, carbsG: 3, fatG: 1.5, sodiumMg: 350, sugarG: 1, fiberG: 0.5 },
  { key: 'ketchup', name: 'Tomato Ketchup', category: 'condiments', serving: '1 tbsp', servingG: 17, calories: 20, proteinG: 0.2, carbsG: 5, fatG: 0, sodiumMg: 160, sugarG: 4, fiberG: 0 },
  { key: 'mayonnaise', name: 'Mayonnaise', category: 'condiments', serving: '1 tbsp', servingG: 14, calories: 95, proteinG: 0.1, carbsG: 0.1, fatG: 10.5, sodiumMg: 90, sugarG: 0.1, fiberG: 0 },
  { key: 'hoisin-sauce', name: 'Hoisin Sauce', category: 'condiments', serving: '1 tbsp', servingG: 16, calories: 35, proteinG: 0.5, carbsG: 7, fatG: 0.5, sodiumMg: 260, sugarG: 4, fiberG: 0.3 },
  { key: 'peanut-sauce-satay', name: 'Peanut Sauce (satay)', category: 'condiments', serving: '2 tbsp', servingG: 30, calories: 110, proteinG: 4, carbsG: 6, fatG: 8, sodiumMg: 280, sugarG: 4, fiberG: 1 },
  { key: 'miso-paste', name: 'Miso Paste', category: 'condiments', serving: '1 tbsp', servingG: 17, calories: 34, proteinG: 2, carbsG: 4, fatG: 1, sodiumMg: 630, sugarG: 1, fiberG: 1 },
  { key: 'xo-sauce', name: 'XO Sauce', category: 'condiments', serving: '1 tbsp', servingG: 15, calories: 60, proteinG: 2, carbsG: 2, fatG: 5, sodiumMg: 400, sugarG: 1, fiberG: 0 },
];
