// Kokoro Health Tracker — Exercise / MET Database + Workout Templates
// Owner: data agent. Plain script (no imports/exports) — assigns to window.
// Schema: { key, name, category: 'cardio'|'strength'|'flexibility'|'sports'|'daily',
//           met, isStrength, muscleGroups: [] }  (muscleGroups only ever uses:
//           'chest','back','legs','shoulders','arms','core')
// MET values approximate the Compendium of Physical Activities.

window.EXERCISE_DB = [
  // ===== cardio =====
  { key: 'walking-slow', name: 'Walking (2.5 mph, leisurely)', category: 'cardio', met: 3.0, isStrength: false, muscleGroups: ['legs'] },
  { key: 'walking-brisk', name: 'Walking (3.5 mph, brisk)', category: 'cardio', met: 4.3, isStrength: false, muscleGroups: ['legs'] },
  { key: 'walking-very-brisk', name: 'Walking (4.5 mph, very brisk)', category: 'cardio', met: 5.0, isStrength: false, muscleGroups: ['legs'] },
  { key: 'jogging-5mph', name: 'Jogging (5 mph)', category: 'cardio', met: 8.3, isStrength: false, muscleGroups: ['legs'] },
  { key: 'running-6mph', name: 'Running (6 mph)', category: 'cardio', met: 9.8, isStrength: false, muscleGroups: ['legs'] },
  { key: 'running-7mph', name: 'Running (7 mph)', category: 'cardio', met: 11.0, isStrength: false, muscleGroups: ['legs'] },
  { key: 'running-8mph', name: 'Running (8 mph)', category: 'cardio', met: 11.8, isStrength: false, muscleGroups: ['legs'] },
  { key: 'running-10mph', name: 'Running (10 mph)', category: 'cardio', met: 14.5, isStrength: false, muscleGroups: ['legs'] },
  { key: 'cycling-leisure', name: 'Cycling (10-12 mph, leisure)', category: 'cardio', met: 6.8, isStrength: false, muscleGroups: ['legs'] },
  { key: 'cycling-moderate', name: 'Cycling (12-14 mph, moderate)', category: 'cardio', met: 8.0, isStrength: false, muscleGroups: ['legs'] },
  { key: 'cycling-vigorous', name: 'Cycling (14-16 mph, vigorous)', category: 'cardio', met: 10.0, isStrength: false, muscleGroups: ['legs'] },
  { key: 'stationary-bike-moderate', name: 'Stationary Bike (moderate)', category: 'cardio', met: 7.0, isStrength: false, muscleGroups: ['legs'] },
  { key: 'swimming-freestyle-moderate', name: 'Swimming (freestyle, moderate)', category: 'cardio', met: 8.3, isStrength: false, muscleGroups: ['chest', 'back', 'arms', 'core', 'legs'] },
  { key: 'swimming-leisurely', name: 'Swimming (leisurely)', category: 'cardio', met: 6.0, isStrength: false, muscleGroups: ['chest', 'back', 'arms', 'legs'] },
  { key: 'swimming-breaststroke', name: 'Swimming (breaststroke)', category: 'cardio', met: 10.3, isStrength: false, muscleGroups: ['chest', 'back', 'arms', 'legs', 'core'] },
  { key: 'rowing-machine-moderate', name: 'Rowing Machine (moderate)', category: 'cardio', met: 7.0, isStrength: false, muscleGroups: ['back', 'arms', 'core', 'legs'] },
  { key: 'rowing-machine-vigorous', name: 'Rowing Machine (vigorous)', category: 'cardio', met: 8.5, isStrength: false, muscleGroups: ['back', 'arms', 'core', 'legs'] },
  { key: 'elliptical-moderate', name: 'Elliptical Trainer (moderate)', category: 'cardio', met: 5.0, isStrength: false, muscleGroups: ['legs', 'arms'] },
  { key: 'stair-climbing-machine', name: 'Stair Climbing Machine', category: 'cardio', met: 8.8, isStrength: false, muscleGroups: ['legs'] },
  { key: 'jump-rope-moderate', name: 'Jump Rope (moderate)', category: 'cardio', met: 11.8, isStrength: false, muscleGroups: ['legs', 'core', 'arms'] },
  { key: 'jump-rope-fast', name: 'Jump Rope (fast)', category: 'cardio', met: 12.3, isStrength: false, muscleGroups: ['legs', 'core', 'arms'] },
  { key: 'hiking-cross-country', name: 'Hiking (cross-country)', category: 'cardio', met: 6.0, isStrength: false, muscleGroups: ['legs', 'core'] },
  { key: 'hiking-hills-pack', name: 'Hiking (hills, with pack)', category: 'cardio', met: 7.8, isStrength: false, muscleGroups: ['legs', 'core', 'back'] },
  { key: 'dancing-general', name: 'Dancing (general, social)', category: 'cardio', met: 4.8, isStrength: false, muscleGroups: ['legs', 'core'] },
  { key: 'zumba', name: 'Zumba', category: 'cardio', met: 6.5, isStrength: false, muscleGroups: ['legs', 'core'] },
  { key: 'kickboxing', name: 'Kickboxing', category: 'cardio', met: 10.3, isStrength: false, muscleGroups: ['core', 'legs', 'arms'] },
  { key: 'hiit-circuit', name: 'HIIT Circuit Training', category: 'cardio', met: 8.0, isStrength: false, muscleGroups: ['core', 'legs', 'arms'] },

  // ===== sports =====
  { key: 'basketball-game', name: 'Basketball (game)', category: 'sports', met: 8.0, isStrength: false, muscleGroups: ['legs', 'core', 'arms'] },
  { key: 'badminton-competitive', name: 'Badminton (competitive)', category: 'sports', met: 7.0, isStrength: false, muscleGroups: ['legs', 'arms', 'core'] },
  { key: 'badminton-casual', name: 'Badminton (casual)', category: 'sports', met: 4.5, isStrength: false, muscleGroups: ['legs', 'arms'] },
  { key: 'soccer-casual', name: 'Soccer (casual)', category: 'sports', met: 7.0, isStrength: false, muscleGroups: ['legs', 'core'] },
  { key: 'soccer-competitive', name: 'Soccer (competitive)', category: 'sports', met: 10.0, isStrength: false, muscleGroups: ['legs', 'core'] },
  { key: 'tennis-singles', name: 'Tennis (singles)', category: 'sports', met: 8.0, isStrength: false, muscleGroups: ['legs', 'arms', 'core'] },
  { key: 'tennis-doubles', name: 'Tennis (doubles)', category: 'sports', met: 6.0, isStrength: false, muscleGroups: ['legs', 'arms'] },
  { key: 'table-tennis', name: 'Table Tennis', category: 'sports', met: 4.0, isStrength: false, muscleGroups: ['arms', 'core'] },
  { key: 'volleyball-casual', name: 'Volleyball (casual/recreational)', category: 'sports', met: 3.0, isStrength: false, muscleGroups: ['legs', 'core', 'arms'] },
  { key: 'golf-walking', name: 'Golf (walking, carrying clubs)', category: 'sports', met: 4.8, isStrength: false, muscleGroups: ['legs', 'arms', 'core'] },

  // ===== daily =====
  { key: 'housework-cleaning', name: 'Housework (general cleaning)', category: 'daily', met: 3.3, isStrength: false, muscleGroups: ['core', 'arms'] },
  { key: 'gardening', name: 'Gardening', category: 'daily', met: 4.0, isStrength: false, muscleGroups: ['back', 'arms', 'core'] },
  { key: 'vacuuming', name: 'Vacuuming', category: 'daily', met: 3.5, isStrength: false, muscleGroups: ['arms', 'core'] },
  { key: 'carrying-groceries', name: 'Carrying Groceries', category: 'daily', met: 4.0, isStrength: false, muscleGroups: ['arms', 'core'] },
  { key: 'playing-with-kids', name: 'Playing with Kids (active)', category: 'daily', met: 3.5, isStrength: false, muscleGroups: ['legs', 'core'] },
  { key: 'stairs-daily', name: 'Climbing Stairs (daily activity)', category: 'daily', met: 4.0, isStrength: false, muscleGroups: ['legs'] },
  { key: 'mowing-lawn-push', name: 'Mowing Lawn (push mower)', category: 'daily', met: 5.5, isStrength: false, muscleGroups: ['legs', 'arms', 'core'] },
  { key: 'washing-car', name: 'Washing the Car', category: 'daily', met: 3.0, isStrength: false, muscleGroups: ['arms', 'core'] },

  // ===== flexibility =====
  { key: 'yoga-hatha', name: 'Yoga (Hatha)', category: 'flexibility', met: 2.5, isStrength: false, muscleGroups: ['core'] },
  { key: 'yoga-power', name: 'Yoga (Power/Vinyasa)', category: 'flexibility', met: 4.0, isStrength: false, muscleGroups: ['core', 'legs', 'arms'] },
  { key: 'pilates', name: 'Pilates', category: 'flexibility', met: 3.0, isStrength: false, muscleGroups: ['core'] },
  { key: 'stretching-general', name: 'Stretching (general)', category: 'flexibility', met: 2.3, isStrength: false, muscleGroups: ['core'] },
  { key: 'tai-chi', name: 'Tai Chi', category: 'flexibility', met: 3.0, isStrength: false, muscleGroups: ['legs', 'core'] },

  // ===== strength =====
  { key: 'bench-press', name: 'Bench Press', category: 'strength', met: 5.0, isStrength: true, muscleGroups: ['chest', 'arms', 'shoulders'] },
  { key: 'squat-barbell', name: 'Barbell Squat', category: 'strength', met: 5.0, isStrength: true, muscleGroups: ['legs', 'core'] },
  { key: 'deadlift', name: 'Deadlift', category: 'strength', met: 6.0, isStrength: true, muscleGroups: ['back', 'legs', 'core'] },
  { key: 'overhead-press', name: 'Overhead Press', category: 'strength', met: 5.0, isStrength: true, muscleGroups: ['shoulders', 'arms'] },
  { key: 'bent-over-row', name: 'Bent-Over Row', category: 'strength', met: 5.0, isStrength: true, muscleGroups: ['back', 'arms'] },
  { key: 'pull-up', name: 'Pull-Up', category: 'strength', met: 8.0, isStrength: true, muscleGroups: ['back', 'arms'] },
  { key: 'push-up', name: 'Push-Up', category: 'strength', met: 8.0, isStrength: true, muscleGroups: ['chest', 'arms', 'core'] },
  { key: 'lunges', name: 'Lunges', category: 'strength', met: 4.0, isStrength: true, muscleGroups: ['legs'] },
  { key: 'leg-press', name: 'Leg Press', category: 'strength', met: 5.0, isStrength: true, muscleGroups: ['legs'] },
  { key: 'bicep-curl', name: 'Bicep Curl', category: 'strength', met: 3.5, isStrength: true, muscleGroups: ['arms'] },
  { key: 'tricep-dip', name: 'Tricep Dip', category: 'strength', met: 4.0, isStrength: true, muscleGroups: ['arms', 'chest'] },
  { key: 'lat-pulldown', name: 'Lat Pulldown', category: 'strength', met: 4.0, isStrength: true, muscleGroups: ['back', 'arms'] },
  { key: 'plank', name: 'Plank', category: 'strength', met: 3.0, isStrength: true, muscleGroups: ['core'] },
  { key: 'crunches', name: 'Crunches', category: 'strength', met: 3.8, isStrength: true, muscleGroups: ['core'] },
  { key: 'hip-thrust', name: 'Hip Thrust', category: 'strength', met: 4.0, isStrength: true, muscleGroups: ['legs', 'core'] },
  { key: 'kettlebell-swing', name: 'Kettlebell Swing', category: 'strength', met: 9.8, isStrength: true, muscleGroups: ['legs', 'core', 'back'] },
  { key: 'circuit-training-weights', name: 'Circuit Training (weights)', category: 'strength', met: 6.0, isStrength: true, muscleGroups: ['chest', 'back', 'legs', 'shoulders', 'arms', 'core'] },
  { key: 'weighted-vest-training', name: 'Weighted Vest Training', category: 'strength', met: 6.0, isStrength: true, muscleGroups: ['legs', 'core'] },
  { key: 'leg-curl-machine', name: 'Leg Curl Machine', category: 'strength', met: 4.0, isStrength: true, muscleGroups: ['legs'] },
  { key: 'chest-fly-machine', name: 'Chest Fly Machine', category: 'strength', met: 4.0, isStrength: true, muscleGroups: ['chest'] },
  { key: 'lateral-raise', name: 'Lateral Raise', category: 'strength', met: 3.5, isStrength: true, muscleGroups: ['shoulders'] },
  { key: 'calf-raise', name: 'Calf Raise', category: 'strength', met: 3.5, isStrength: true, muscleGroups: ['legs'] },
];

// Schema: { key, name, goal: 'lose'|'maintain'|'gain', level: 'beginner'|'intermediate'|'advanced',
//           daysPerWeek, description, days: [ { title, focus, items: ['...'] } ] }
window.WORKOUT_TEMPLATES = [
  {
    key: 'full-body-3x',
    name: 'Full-Body Strength (3x/week)',
    goal: 'maintain',
    level: 'beginner',
    daysPerWeek: 3,
    description: 'A balanced 3-day full-body routine hitting every major muscle group each session — ideal for beginners building a strength base.',
    days: [
      { title: 'Day 1 - Full Body A', focus: 'Full body', items: ['Barbell Squat 3x8', 'Bench Press 3x8', 'Bent-Over Row 3x10', 'Plank 3x30s', 'Stretching 10min'] },
      { title: 'Day 2 - Full Body B', focus: 'Full body', items: ['Deadlift 3x6', 'Overhead Press 3x8', 'Lat Pulldown 3x10', 'Crunches 3x15', 'Stretching 10min'] },
      { title: 'Day 3 - Full Body C', focus: 'Full body', items: ['Leg Press 3x10', 'Push-Up 3x12', 'Bicep Curl 3x12', 'Tricep Dip 3x12', 'Hip Thrust 3x10'] },
    ],
  },
  {
    key: 'push-pull-legs',
    name: 'Push / Pull / Legs Split',
    goal: 'gain',
    level: 'intermediate',
    daysPerWeek: 6,
    description: 'Classic 6-day PPL split for hypertrophy — two cycles per week for higher training frequency.',
    days: [
      { title: 'Day 1 - Push', focus: 'Chest, shoulders, triceps', items: ['Bench Press 4x8', 'Overhead Press 3x10', 'Chest Fly Machine 3x12', 'Lateral Raise 3x15', 'Tricep Dip 3x12'] },
      { title: 'Day 2 - Pull', focus: 'Back, biceps', items: ['Deadlift 3x6', 'Bent-Over Row 4x8', 'Pull-Up 3x8', 'Lat Pulldown 3x10', 'Bicep Curl 3x12'] },
      { title: 'Day 3 - Legs', focus: 'Quads, hamstrings, glutes, calves', items: ['Barbell Squat 4x8', 'Leg Press 3x10', 'Leg Curl Machine 3x12', 'Hip Thrust 3x10', 'Calf Raise 4x15'] },
      { title: 'Day 4 - Push', focus: 'Chest, shoulders, triceps', items: ['Bench Press 3x10', 'Overhead Press 3x8', 'Lateral Raise 3x15', 'Tricep Dip 3x15'] },
      { title: 'Day 5 - Pull', focus: 'Back, biceps', items: ['Bent-Over Row 3x10', 'Pull-Up 3x10', 'Lat Pulldown 3x12', 'Bicep Curl 3x15'] },
      { title: 'Day 6 - Legs', focus: 'Quads, hamstrings, glutes, calves', items: ['Barbell Squat 3x10', 'Leg Press 3x12', 'Hip Thrust 3x12', 'Calf Raise 3x20'] },
    ],
  },
  {
    key: 'upper-lower',
    name: 'Upper / Lower Split',
    goal: 'gain',
    level: 'intermediate',
    daysPerWeek: 4,
    description: 'A 4-day upper/lower split balancing strength and hypertrophy with adequate recovery.',
    days: [
      { title: 'Day 1 - Upper', focus: 'Chest, back, shoulders, arms', items: ['Bench Press 4x8', 'Bent-Over Row 4x8', 'Overhead Press 3x10', 'Lat Pulldown 3x10', 'Bicep Curl 3x12', 'Tricep Dip 3x12'] },
      { title: 'Day 2 - Lower', focus: 'Legs, core', items: ['Barbell Squat 4x8', 'Deadlift 3x6', 'Leg Press 3x10', 'Hip Thrust 3x10', 'Plank 3x40s'] },
      { title: 'Day 3 - Upper', focus: 'Chest, back, shoulders, arms', items: ['Overhead Press 4x8', 'Pull-Up 3x8', 'Chest Fly Machine 3x12', 'Lateral Raise 3x15', 'Bicep Curl 3x12'] },
      { title: 'Day 4 - Lower', focus: 'Legs, core', items: ['Leg Press 4x10', 'Leg Curl Machine 3x12', 'Calf Raise 4x15', 'Crunches 3x20'] },
    ],
  },
  {
    key: 'couch-to-5k',
    name: 'Couch to 5K (Cardio Build-Up)',
    goal: 'lose',
    level: 'beginner',
    daysPerWeek: 3,
    description: 'A beginner-friendly walk/jog interval progression building up to running 5K continuously.',
    days: [
      { title: 'Day 1 - Intervals', focus: 'Run/walk intervals', items: ['Walking (brisk) 5min warm-up', 'Jog 1min / Walk 2min x8', 'Walking (brisk) 5min cool-down'] },
      { title: 'Day 2 - Intervals', focus: 'Run/walk intervals', items: ['Walking (brisk) 5min warm-up', 'Jog 2min / Walk 2min x6', 'Walking (brisk) 5min cool-down'] },
      { title: 'Day 3 - Longer Intervals', focus: 'Run/walk intervals', items: ['Walking (brisk) 5min warm-up', 'Jog 3min / Walk 90s x5', 'Walking (brisk) 5min cool-down', 'Stretching 10min'] },
    ],
  },
  {
    key: 'hiit-fat-loss',
    name: 'HIIT Fat-Loss Circuit',
    goal: 'lose',
    level: 'intermediate',
    daysPerWeek: 4,
    description: 'High-intensity interval circuits combined with light strength work to maximize calorie burn.',
    days: [
      { title: 'Day 1 - HIIT Circuit', focus: 'Full body conditioning', items: ['HIIT Circuit Training 20min', 'Kettlebell Swing 4x15', 'Plank 3x40s'] },
      { title: 'Day 2 - Steady Cardio', focus: 'Cardio endurance', items: ['Cycling (moderate) 30min', 'Stretching 10min'] },
      { title: 'Day 3 - HIIT + Core', focus: 'Conditioning, core', items: ['Jump Rope (fast) 5x2min', 'Crunches 3x20', 'Push-Up 3x15'] },
      { title: 'Day 4 - Active Recovery', focus: 'Mobility, light cardio', items: ['Walking (brisk) 30min', 'Yoga (Hatha) 20min'] },
    ],
  },
  {
    key: 'hypertrophy-5-day',
    name: '5-Day Hypertrophy Split',
    goal: 'gain',
    level: 'advanced',
    daysPerWeek: 5,
    description: 'A body-part split for advanced lifters targeting maximal muscle growth with high volume per group.',
    days: [
      { title: 'Day 1 - Chest', focus: 'Chest, triceps', items: ['Bench Press 5x8', 'Chest Fly Machine 4x12', 'Tricep Dip 4x12', 'Push-Up 3xAMRAP'] },
      { title: 'Day 2 - Back', focus: 'Back, biceps', items: ['Deadlift 4x6', 'Bent-Over Row 4x10', 'Pull-Up 4x8', 'Lat Pulldown 3x12', 'Bicep Curl 3x12'] },
      { title: 'Day 3 - Legs', focus: 'Quads, hamstrings, glutes, calves', items: ['Barbell Squat 5x8', 'Leg Press 4x10', 'Leg Curl Machine 4x12', 'Hip Thrust 3x12', 'Calf Raise 4x20'] },
      { title: 'Day 4 - Shoulders', focus: 'Shoulders, core', items: ['Overhead Press 4x8', 'Lateral Raise 4x15', 'Plank 3x45s', 'Crunches 3x20'] },
      { title: 'Day 5 - Arms', focus: 'Arms, accessory', items: ['Bicep Curl 4x12', 'Tricep Dip 4x12', 'Lat Pulldown 3x12', 'Chest Fly Machine 3x12'] },
    ],
  },
  {
    key: 'active-recovery-mobility',
    name: 'Mobility & Active Recovery',
    goal: 'maintain',
    level: 'beginner',
    daysPerWeek: 2,
    description: 'Low-intensity mobility and flexibility sessions to support recovery between harder training days.',
    days: [
      { title: 'Day 1 - Mobility Flow', focus: 'Flexibility, joints', items: ['Yoga (Hatha) 30min', 'Stretching (general) 15min'] },
      { title: 'Day 2 - Gentle Movement', focus: 'Low-impact cardio, mobility', items: ['Walking (leisurely) 30min', 'Tai Chi 20min', 'Stretching (general) 15min'] },
    ],
  },
];
